### ISSUE TITLE
I can't create issues in your K666 repository.

### ISSUE THREAD

**Issue by procrasti** [orionblastar/FreeK666backup#9]
I was able to check in stuff to it though...

Seems odd.

**Comment by orionblastar** [comment]
I can't create issues either. 

http://webapps.stackexchange.com/questions/53586/how-to-report-a-bug-to-a-github-project-that-is-missing-an-issues-page

Did you enable issues in your main K666 repo? If not and you did it so K5 trolls couldn't leave fake info and fake issues then when I forked it, it took your settings of not having issues available. I am trying to use issues here to fix things. I've been working since I got up around 10am or so until 2pm now to see how much I could do. It is hard with no issues on OB/K666 so I have to come here and look.

**Comment by orionblastar** [comment]
I fixed it, in settings the issues option was checked off. I checked it to on instead so we can have issues there.
